apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
    spec:
      containers:
      - image: swr.cn-north-1.myhuaweicloud.com/zhf/demo-go-auto:119f8a1911120cc98d9a5802d62ce5cb1a3955be
        name: demo-go
        ports:
        - containerPort: 8888
