apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
    spec:
      containers:
      - image: swr.cn-north-1.myhuaweicloud.com/zhf/demo-go-auto:16640d98ed0311db93757e2f1513d9a5781a1c76
        name: demo-go
        ports:
        - containerPort: 8888
