apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
    spec:
      containers:
      - image: swr.cn-north-1.myhuaweicloud.com/zhf/demo-go-auto:6d86f70b64e7ca3ca71106f2412223eeb2d2c02d
        name: demo-go
        ports:
        - containerPort: 8888
