apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
    spec:
      containers:
      - image: swr.cn-north-1.myhuaweicloud.com/zhf/demo-go-auto:f6e6fc29bfa38b1a7b7888d7f2fa6238e20f2ce5
        name: demo-go
        ports:
        - containerPort: 8888
